# Generated by Django 3.0.5 on 2020-04-28 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_user_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogPost',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog post'},
        ),
    ]
