# Generated by Django 3.0.5 on 2020-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_status_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='featured',
            field=models.TextField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Draft')], default=0),
        ),
    ]
