# Generated by Django 3.0.5 on 2020-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20200423_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='featured',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Draft')], default=0),
        ),
    ]
