# Generated by Django 3.0.5 on 2020-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20200423_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
