# Generated by Django 3.0.5 on 2020-04-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_status_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-id'], 'verbose_name': 'Status post', 'verbose_name_plural': 'Status posts'},
        ),
    ]
